id: 12c7e452ab6c484a9a73e5d38e022cc8
initial_creation_type: ocr
source_metadata:
  volumes:
    90c19ee0e3844c71a17ef7f398e8d499:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: གཤིན་རྗེ་གཤེད་རྡོ་རྗེ་རྣོན་པོ་ཞེས་བྱ་བའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
